image:  Windows 10 # образ для сборки
stack: node 12 # окружение
branches:
  only:
  - main # ветка гит
cache: node_modules # кеширование
install: 
  - npm install # команда установки зависимостей
build: off
test_script:
  - npm run lint && npm test # скрипт сборки